@startuml 초기설계
start
 :tourUML;

if (여행을 안내해드릴까요?) then (yes)
	:가고싶은 여행지 선택;

	if (혼자가세요?) then (yes)
		:혼자 즐길수 있는 여행유형;
		- 원하시는 여행유형은?
		- 원하시는 음식취향은?
		- 혼자가볼만한 장소는?

	else (no)
		:함께 즐길수 있는 여행유형;
		- 예산안에서 함께 먹을만한 음식은?
		- 함께 늘길만한 놀거리는?
		- 함께 가볼만한 장소는?
	endif

else (no)
:추천 여행지 선택;
endif

@enduml